language: ruby
# only install ci and assets gems:
bundler_args: --without production:development:test
sudo: false
cache: bundler
env:
  - RAKE_TASK=test
  - RAKE_TASK=test:pages:all
rvm:
  - 2.1.5
matrix:
  fast_finish: true
#  allow_failures:
#    - rvm: 2.0.0
addons:
  apt:
    packages:
      - graphicsmagick
      - inkscape
before_install:
  - "bundle --version"
before_script:
  - "cp config/database.yml.example config/database.yml"
  - "bundle exec rake db:create"
  - "bundle exec rake db:schema:load"
  - "bundle exec rake db:test:prepare"
  - "RAILS_ENV=test bundle exec rake db:fixtures:load"
  - "RAILS_ENV=test bundle exec rake ts:index ts:start"
script: "bundle exec rake $RAKE_TASK"
after_script:
  - "cat tmp/*.test*.log" # printing logs from the failed integration tests
notifications:
  email: false

