#
# Please do not enable sites in this file.
#
# The problem is that some tests assume there are no sites, and some
# assume there are sites, and you should also be able to test both situations
# if you so desire.
#
# So, you can use Conf.enable_site_testing and Conf.disable_site_testing in
# your tests to selectively turn on and off sites.
#

title: "Crabgrass Testing"

raise_i18n_exceptions: true
enforce_ssl: false
pagination_size: 5
